// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace NguyenThiNgoc535.Migrations
{
    [DbContext(typeof(KiemTraDbContext))]
    [Migration("20211215061907_Create_Table_NTN0535")]
    partial class Create_Table_NTN0535
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("NguyenThiNgoc535.Models.CompanyNTN535", b =>
                {
                    b.Property<string>("CompanyId")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("CompanyId");

                    b.ToTable("CompanyNTN535s");
                });

            modelBuilder.Entity("NguyenThiNgoc535.Models.NTN0535", b =>
                {
                    b.Property<string>("NTNId")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("NTNGender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NTNName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("NTNId");

                    b.ToTable("NTN0535s");
                });
#pragma warning restore 612, 618
        }
    }
}
